### ISSUE TITLE
CP采集流量问题咨询

### ISSUE THREAD

**Issue by baodarentian** [Netis/cloud-probe#167]
使用daemonset方式部署cp时，如果某业务pod有两个网口配置不同IP，且同时都有业务流量，是否支持两个网口都采集？如果不支持，是否可以选择某个网口来采集？

**Comment by robbietu** [comment]
目前不支持该功能，默认采集eth0流量，不可选择网口。

**Comment by robbietu** [comment]
目前不支持该功能，默认采集pod中eth0流量，不可选择网口。
