### ISSUE TITLE
arm架构的麒麟系统安装我们的cp后，用户反馈系统普通用户无法登录sftp，root用户可以

### ISSUE THREAD

**Issue by KevinDu2023** [Netis/cloud-probe#179]
<img width="213" alt="1722929025991" src="https://github.com/user-attachments/assets/8c19bbc6-8022-4a86-be2a-84783726f3ef">
如图，用户反馈安装前普通用户是可以登录sftp的，并且x86架构的麒麟系统安装cp后不受影响
安装包分别是：netis-cloud-probe-0.7.4.aarch64_kylin.rpm 和 netis-cloud-probe-0.7.4.x86_64_kylin.rpm

**Comment by KevinDu2023** [comment]
arm架构服务器麒麟V10 SP2和SP3安装探针后普通用户sftp登录异常。

**Comment by robbietu** [comment]
请按流程安排task排查，谢谢
