### ISSUE TITLE
cp增加限速配置后丢包

### ISSUE THREAD

**Issue by KevinDu2023** [Netis/cloud-probe#182]
*Note: In order to provide a more accurate response to your issue, please present your issue using the template.*

# Environment

*Note：Include the following detailes, among others:*

* *CP version*   0.8
* *Operation System(OS)*    centos 7.3，如下图
* *platform（e.g., vm, pod, etc）** 阿里云的虚拟机
![f8fb899100b927ad8a07de00ee13f8fb_compress](https://github.com/user-attachments/assets/f960167c-d312-49d9-8e54-b7a7d0c96348)

# Issue description

cp增加限速配置后丢包，cp转发流量2M左右，限速配置了1000M，还是有波动，配置2000M后有缓解，不配置限速就没有任何问题，需要了解下为什么会有这个问题，图片是配置了2000M的命令。

这个问题提过SR，判断下来是cp丢包

![3cd44d7c44cf442a5700dfc00e5bcae0_compress](https://github.com/user-attachments/assets/58b9af98-f313-4998-8186-e9f9e49a2032)

**Comment by robbietu** [comment]
CP限流实现的机制是从tcprelay复制过来的。具体的实现限流配置的带宽会换算为微秒级。代码如下：
                            delta_us = (uint64_t)(_send_bytes / _Bpus);
                            tick_us = _first_send_us + delta_us;
                            if(us < tick_us)
                                return -1;
                            tick_us = _first_send_us + delta_us + __TRAFFIC_GAP_US; //traffic gap
                            if(us > tick_us)
                            {
                                _first_send_us = us;
                                _send_bytes = 0;
                            }
                        }

- delta_us 表示由于已经发送的数据量 _send_bytes 而推迟的时间间隔，将发送的字节数除以每微秒的字节数，得出的结果是发送这些字节所消耗的时间
- tick_us 表示期望的发送时间，等于初始发送时间 _first_send_us 加上 delta_us
- 检查当前的时间 us 是否小于计算出来的 tick_us。如果 us 还没有到达 tick_us，说明发送的速度太快，程序需要等待，所以返回 -1 来限制流量。
- 后面重新计算 tick_us，在之前的基础上加上了一个额外的流量间隔（__TRAFFIC_GAP_US），这个值代表流量控制中的预期发送间隔，防止流量过于集中或不均匀。
- 最后如果当前时间 us 已经超过了 tick_us，说明流量间隔已经到达，需要重新开始计算。

**Comment by robbietu** [comment]
将以上if(us < tick_us)改为 if((us < tick_us)&&(tick_us - us) > 100000) ，以适应流量抖动。
