### ISSUE TITLE
PA在封装报文时，实际报文之间相差100ms，但是封装过后，报文相差不足1ms

### ISSUE THREAD

**Issue by KevinDu2023** [Netis/cloud-probe#186]
*Note: In order to provide a more accurate response to your issue, please present your issue using the template.*

# Environment

*Note：Include the following detailes, among others:*

* *CP version*  0.7.4、0.8.0
* *Operation System(OS)* Centos 7.9
* *platform（e.g., vm, pod, etc）** 微探针

# Issue description
测试环境复现了这个结果，经过vxlan封装后的req和resp的时间相差就会变得很短，实际报文之间相差100ms，封装后相差1ms.

**Comment by robbietu** [comment]
需要进一步调研该问题，请联系Eva走流程排期。
