### ISSUE TITLE
pktminerg的报错日志

### ISSUE THREAD

**Issue by KevinDu2023** [Netis/cloud-probe#187]
Hi
cp版本：netis-cloud-probe-0.7.4.x86_64_kylin.rpm
k8s环境中pod的日志：pktminerg会报这个错，请问下是什么原因：
Call pcap_activate failed error is SIOCGIFHWADDR: No such device
![image](https://github.com/user-attachments/assets/8a88034c-3a7d-4103-b14a-449e70e51e99)

**Comment by robbietu** [comment]
这个错误代表网卡找不到，也许是策略中网卡名错误，也许是网卡绑定网卡出错。

**Comment by KevinDu2023** [comment]
那为什么后面也会出来采集数据的日志，但是会时不时报这个错误。

**Comment by robbietu** [comment]
这个错误是libpcap的接口函数pcap_activate报的。说明时而调用失败，时而用成功。如果需要进一步调研这个问题，需要复现这样的系统环境。
